import ClaimHcfaPdfSkeleton from "@/components/skeleton_loader/ManagedCareSkeleton/ClaimsSkeleton/ClaimsHcfaPdfSkeleton/ClaimsHcfaPdfSkeleton";
import dynamic from "next/dynamic";
import Head from "next/head";

const ClaimsHcfaPdfViewerComponent = dynamic(
  () => import("managedCare/ClaimHcfaPdfViewer"),
  {
    ssr: false,
    loading: () => <ClaimHcfaPdfSkeleton />,
  }
);

export default function Claims() {
  return (
    <>
      <Head>
        <title>IRIS | Claims</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ClaimsHcfaPdfViewerComponent />
    </>
  );
}
