import ClaimsSkeleton from "@/components/skeleton_loader/ManagedCareSkeleton/ClaimsSkeleton/ClaimsSkeleton";
import dynamic from "next/dynamic";
import Head from "next/head";

const ClaimsComponent = dynamic(() => import("managedCare/Claims"), {
  ssr: false,
  loading: () => <ClaimsSkeleton />,
});

export default function Claims() {
  return (
    <>
      <Head>
        <title>IRIS | Claims</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ClaimsComponent />
    </>
  );
}
