export const APPOINTMENT_CONFIRMATION_COOKIE_DATA = "APPT_CONFIRM_DATA";

export const APPOINTMENT_CONFIRMATION_COOKIE_FLOW = {
  STRAIGHT_REDIRECTION: "APPT_SHT_RRT",
  INTAKE_FORM_REDIRECTION: "APPT_INK_RRT",
}
