//INFO: To load specific filter page wise we need to use this object inside getStaticProps
//INFO: This is used to preselect filters on page load
export const facetKeyMappingWithPathName = {
  CATALOG_EYEGLASSES: `p=categoryPath:"Glasses>Eyeglasses"&filter=vHasHisResImage:true`,
  CATALOG_MEN_EYEGLASSES: `p=categoryPath:"Glasses>Eyeglasses>Men"&filter=vHasHisResImage:true`,
  CATALOG_WOMEN_EYEGLASSES: `p=categoryPath:"Glasses>Eyeglasses>Women"&filter=vHasHisResImage:true`,
  CATALOG_YOUTH_EYEGLASSES: `p=categoryPath:"Glasses>Eyeglasses>Kids"&filter=vHasHisResImage:true`,
  CATALOG_SUNGLASSES: `p=categoryPath:"Glasses>Sunglasses"&filter=vHasHisResImage:true`,
  CATALOG_MEN_SUNGLASSES: `p=categoryPath:"Glasses>Sunglasses>Men"&filter=vHasHisResImage:true`,
  CATALOG_WOMEN_SUNGLASSES: `p=categoryPath:"Glasses>Sunglasses>Women"&filter=vHasHisResImage:true`,
  CATALOG_DAILY_CONTACTS: `p=categoryPath:"Contacts>Daily"`,
  CATALOG_MONTHLY_CONTACTS: `p=categoryPath:"Contacts>Monthly"`,
  CATALOG_BIWEEKLY_CONTACTS: `p=categoryPath:"Contacts>Biweekly"`,
  CATALOG_CONTACTS: `p=categoryPath:"Contacts"`,
  CATALOG_VISION_SUPPLEMENTS: `p=categoryPath:"EyeHealth>VisionSupplimnets"`,
  CATALOG_EYECARE_PRODUCTS: `p=categoryPath:"EyeHealth>EyeCareProducts"`,
  CATALOG_ALLEYEHEALTH_PRODUCTS: `p=categoryPath:"EyeHealth"`,
  EYEGLASSES_UNDER_50: `p=categoryPath:"eyeglasses>glasses-under-50"&filter=vHasHisResImage:true`,
  EYEGLASSES_METAL_FRAMES: `p=categoryPath:"eyeglasses>metal-frames"&filter=vHasHisResImage:true`,
  EYEGLASSES_PLASTIC_FRAMES: `p=categoryPath:"eyeglasses>plastic-frames"&filter=vHasHisResImage:true`,
  EYEGLASSES_RIMLESS_FRAMES: `p=categoryPath:"eyeglasses>rimless-frames"&filter=vHasHisResImage:true`,
  EYEGLASSES_CAT_EYE_FRAMES: `p=categoryPath:"eyeglasses>cat-eye-frames"&filter=vHasHisResImage:true`,
  EYEGLASSES_ROUND_FRAMES: `p=categoryPath:"eyeglasses>round-frames"&filter=vHasHisResImage:true`,
  EYEGLASSES_OVAL_FRAMES: `p=categoryPath:"eyeglasses>oval-frames"&filter=vHasHisResImage:true`,
  EYEGLASSES_RECTANGLE_FRAMES: `p=categoryPath:"eyeglasses>rectangle-frames"&filter=vHasHisResImage:true`,
  EYEGLASSES_SQUARE_FRAMES: `p=categoryPath:"eyeglasses>square-frames"&filter=vHasHisResImage:true`,
  SUNGLASSES_UNDER_50: `p=categoryPath:"sunglasses>sunglasses-under-50"&filter=vHasHisResImage:true`,
  SUNGLASSES_METAL_FRAMES: `p=categoryPath:"sunglasses>metal-frames"&filter=vHasHisResImage:true`,
  SUNGLASSES_PLASTIC_FRAMES: `p=categoryPath:"sunglasses>plastic-frames"&filter=vHasHisResImage:true`,
  SUNGLASSES_CAT_EYE_FRAMES: `p=categoryPath:"sunglasses>cat-eye-frames"&filter=vHasHisResImage:true`,
  SUNGLASSES_ROUND_FRAMES: `p=categoryPath:"sunglasses>round-frames"&filter=vHasHisResImage:true`,
  SUNGLASSES_OVAL_FRAMES: `p=categoryPath:"sunglasses>oval-frames"&filter=vHasHisResImage:true`,
  SUNGLASSES_RECTANGLE_FRAMES: `p=categoryPath:"sunglasses>rectangle-frames"&filter=vHasHisResImage:true`,
  SUNGLASSES_SQUARE_FRAMES: `p=categoryPath:"sunglasses>square-frames"&filter=vHasHisResImage:true`,
  BEST_SELLER_GLASSES: `p=categoryPath:"best-seller-glasses"&filter=vHasHisResImage:true`,
  NEW_ARRIVAL_GLASSES: `p=categoryPath:"Glasses>Eyeglasses>Brand>Elite"&filter=vHasHisResImage:true`
};

export const CatalogCategoryPathCheck = {
  ALL_FRAMES: "/catalog/all-frames",
  CATALOG_ALL_EYEGLASSES: "/catalog/eyeglasses",
  CATALOG_MEN: "men",
  CATALOG_WOMEN: "women",
  CATALOG_KIDS: "youth",
  CATALOG_METAL: "metal",
  CATALOG_PLASTIC: "plastic",
  CATALOG_RIMLESS: "rimless",
  CATALOG_CAT_EYE: "cat-eye",
  CATALOG_ROUND: "round",
  CATALOG_OVAL: "oval",
  CATALOG_RECTANGLE: "rectangle",
  CATALOG_SQUARE: "square",
  CATALOG_ALL_SUNGLASSES: "/catalog/sunglasses",
  VISION_SUPPLEMENTS: "/catalog/vision-supplements",
  BEST_SELLER_GLASSES: "/best-seller-glasses",
  NEW_ARRIVAL_GLASSES: "/catalog/new-arrivals"
};
