export const GA_TAG_EVENTS = {
  VIEW_ITEM_LIST:"view_item_list",
  SELECT_ITEM:"select_item",
  VIEW_ITEM:"view_item",
  ADD_TO_CART:"add_to_cart",
  VIEW_CART:"view_cart",
  REMOVE_FROM_CART:"remove_from_cart",
  BEGIN_CHECKOUT:"begin_checkout",
  ADD_SHIPPING_INFO:"add_shipping_info",
  ADD_PAYMENT_INFO:"add_payment_info",
  PURCHASE:"purchase",
  REFUND:"refund",
  VIEW_PROMOTION:"view_promotion",
  SELECT_PROMOTION: "select_promotion",
  ADD_TO_CART_LENS_MATERIAL:"addToCart-lens_material",
  ADD_TO_CART_LENS_TYPE:"addToCart-lens_type",
  ADD_TO_CART_PRESCRIPTION_TYPE:"addToCart-prescription_type",
  ADD_PRESCRIPTION_STEP: "add_prescription_step",
  ADD_TO_CART_SUMMARY:"addToCart-summary",
  ADDTOCART:"addToCart",
  CANCELED_APPOINTMENT:"canceled_appointment",
  MODIFIED_APPOINTMENT:"modified_appointment",
  PROMO_APPLIED:"apply_promo",
  INSURANCE_ELIGIBILITY:"insurance_eligibility",
  EXAM_TYPE: "examType",
  DATE_OF_BIRTH: "dateOfBirth",
  DATE_SELECTION:"dateSelection",
  NEW_OR_EXISTING:"newOrExisting",
  APPOINTMENT:"appointment",
  GOOGLE_MAP_API_CALL:"googleMapsApiCall",
  MAPS_API_SEARCH_ORIGIN: "mapsApiSearchOrigin",
  MAPS_API_SEARCH_TERM: "mapsApiSearchTerm",
  STORE_ID: "storeID",
  STORE_NAME: "storeName",
  STORE_ADDRESS: "storeAddress",
  TIME_FRAME: "timeFrame",
  TIME: "time",
  PROMO_CODE: "promo_code",
  CHECK_ORDER_STATUS: "check_order_status",
  HEADER_SIGN_IN: "header_sign_in",
  FOOTER_SIGN_UP: "footer_sign_me_up",
  BOOK_EYE_EXAM_Q1: "book_eye_exam_q1",
  BOOK_EYE_EXAM_Q2: "book_eye_exam_q2",
  EXISTING: "existing",
  NEW: "new",
  STORE_VISIT: "store_visit",
};


export const GA_TAG_VARIABLE_PRODUCT = "ecommerce";
