const Permission = {
  MENU: {
    OPERATION: {
      CLINICAL_SCHEDULER: ["Scheduler_GetClinicalSchedule"],
      OPERATION_COMMAND: ["Order_GetDataForOperationCommandCenter"],
      VIRTUAL_OPTICIAN: [
        "VirtualOptician_GetAllNewVtoOrders",
        "VirtualOptician_GetAllDispensedVtoOrders",
        "VirtualOptician_GetAllCompleteVtoOrders",
      ],
      CLOSING: ["Order_GetStoreClosingDetails"],
      CLOSING_HISTORY: ["Order_GetStoreClosingDetails"],
      INVENTORY_COUNT: ["Inventory_GetCycleCountDetailsByStoreId"],
      INVENTORY_ADJUSTMENT: ["Inventory_GetInventoryAdjustmentHistory"],
      INVENTORY_REPLENISHMENT: ["Inventory_GetAllReplenishmentRequests"],
      RETURN_TO_CREDIT: ["Inventory_GetAllSubmittedReturnForms"],
      CC_REPORT: ["Order_GetCashCollectionReport"],
      CONTACT_LENS_CALCULATOR: ["OrderSetup_CalculateContactLensRebate"],
      MANAGE_CARE_CLAIMS: ["ManagedCare_GetBillingClaimGrid"],
      MANAGE_CARE_BENEFITS_SHEET: ["Setup_GetBenefitSheetGrid"],
      PENDING_WEB_ORDERS: ["Order_GetPendingWebOrderGrid"],
    },
    JOB_TRACKING: {
      JOB_STATUS: ["Order_GetOrderStatuses"],
      JOB_STATUS_HISTORY: [
        "Order_GetDistributionCenters",
        "Order_GetOrderStatuses",
      ],
      STAGING_BIN_VIEW: ["Order_GetFrameStagingBin"],
      PENDING_SHIP: ["Order_GetFrameStagingBin"],
      PENDING_TRACE: ["Order_GetFrameStagingBin"],
    },
    TABLET_CHECK_IN: ["Scheduler_GetTabletCheckInDetails"],
    CART: ["Order_GetStoreAllCartDetails"],
    SETTINGS: {
      DC_SETUP: ["OrderSetup_GetAllDistributionCenterWithGrid"],
      IMPORT_SETUP: ["MasterSetup_GetAllFileImportsInGrid"],
      INTAKE_SETUP: ["IntakeFormSetup_GetAll"],
      MANAGE_CARE_SETUP: [
        "Setup_GetClaimStatusGrid",
        "Setup_GetCptCodeById",
        "Setup_GetInsuranceCarrierGrid",
        "Setup_GetAllInsuranceCarrierCredentials",
        "Setup_GetRuleGrid",
        "Setup_GetBenefitSheetGrid",
      ],
      MASTER_SETUP: [
        "MasterSetup_GetAllCountriesInGrid",
        "MasterSetup_GetAllStatesInGrid",
        "MasterSetup_GetAllCountiesInGrid",
        "MasterSetup_GetAllCitiesInGrid",
        "MasterSetup_GetAllZipsWithGrid",
        "MasterSetup_GetMasterLookUps",
        "MasterSetup_GetAllMessages",
        "MasterSetup_GetAllConfigurations",
        "MasterSetup_GetAllPatientNoteCategoryWithGrid",
        "MasterSetup_GetAllRelationshipTypeWithGrid",
        "MasterSetup_GetPaperCaptureSubCategoriesGrid",
        "MasterSetup_GetAllFailedQueueRequestsGrid",
      ],
      ORDER_SETUP: [
        "OrderSetup_GetAllJobHubRuleWithGrid",
        "OrderSetup_GetAllLabTypeWithGrid",
        "OrderSetup_GetAllTenderTypeWithGrid",
        "OrderSetup_GetAllTenderTypeWithGrid",
        "OrderSetup_GetAlCourierServiceProviderGrid",
        "OrderSetup_GetAllRemakeReasonWithGrid",
        "OrderSetup_GetAllDcCutOutFormulaWithGrid",
        "OrderSetup_GetAllLabRxRangeWithGrid",
        "OrderSetup_GetAllOrderStatusCodeWithGrid",
        "OrderSetup_GetAllPaymentLimits",
        "OrderSetup_GetAllOrderStatusCodeSequencingWithGrid",
        "OrderSetup_GetAllOrderStatusCodeGroupWithGrid",
      ],
      PATIENT_COMMUNICATION_SETUP: [
        "PatientCommunicationSetup_GetAllMyAccountPatientCommunication",
        "PatientCommunicationSetup_GetAllDemographicsPatientCommunication",
        "PatientCommunicationSetup_GetAllOrderPatientCommunication",
        "PatientCommunicationSetup_GetAllSchedulingPatientCommunication",
        "PatientCommunicationSetup_GetAllStantonAccessPatientCommunication"
      ],
      SCHEDULER_SETUP: [
        "SchedulerSetup_GetAppointmentTypesGrid",
        "SchedulerSetup_GetAppointmentStatusGrid",
        "SchedulerSetup_GetWorkingHourConfigInGrid",
        "SchedulerSetup_GetAllNonWorkingHours",
        "SchedulerSetup_GetStoreNotesGrid",
        "SchedulerSetup_GetSchedulerStoreNoteCategoryGrid",
        "SchedulerSetup_GetDoubleBookingRulesGrid",
        "SchedulerSetup_GetAgeRestrictionsGrid",
        "SchedulerSetup_GetGeneralSettingsGrid",
      ],
      STORE_SETUP: [
        "StoreSetup_GetAllStoreWithGrid",
        "StoreSetup_GetAllStoreBrandInGrid",
        "StoreSetup_GetAllMarketingDmaInGrid",
        "StoreSetup_GetAllDistrictInGrid",
        "StoreSetup_GetAllStoreDeviceWithGrid",
      ],
      USER_ROLE_SETUP: [
        "UserSetup_GetAllUsersWithGrid",
        "UserSetup_GetAllUserTypeWithGrid",
        "UserSetup_GetAllRolesWithGrid",
      ],
      PROMOTION_LOYALTY_SETUP: [
        "OrderSetup_GetPromotionGrid",
        "OrderSetup_GetAllLoyaltyClubDetailsWithGrid",
      ],
      CONTACT_LENS_REBATE_SETUP: [
        "OrderSetup_GetManufacturerRebateUrlGrid",
        "OrderSetup_GetContactLensRebateGrid",
      ],
    },
  },
};

export default Permission;
