// IR-2328: Added mobile menu
import { NavItem } from "@/types/Header.types";
import { NAV_ITEMS } from "./header.constants";

export const MOBILE_NAV_ITEMS: NavItem[] = [
  {
    id: "eh1-drop",
    name: "EYE_HEALTH",
    subMenu: [
      {
        id: "eh1-drop-vs-pg-1",
        url: "/catalog/vision-supplements/",
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        subMenu: [],
        name: "VISION_SUPPLEMENTS",
      },
      {
        id: "eh1-drop-ecp-pg-2",
        url: "/catalog/eye-care-products/",
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        subMenu: [],
        name: "EYE_CARE_PRODUCTS",
      },
      {
        id: "eh1-drop-ehg-pg-3",
        url: "/blog",
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        subMenu: [],
        name: "EYE_HEALTH_GUIDE",
      },
      {
        id: "eh1-drop-bee-pg-4",
        url: "/book-eye-exam",
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        subMenu: [],
        name: "BOOK_EYE_EXAM",
      },
    ],
    type: NAV_ITEMS.NAV_TYPES.DROPDOWN,
    url: "",
  },
  {
    id: "e2-drop",
    type: NAV_ITEMS.NAV_TYPES.DROPDOWN,
    name: "EYEGLASSES",
    subMenu: [
      {
        id: "e2-drop-w-pg-1",
        name: "WOMEN",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/womens-eyeglasses/",
      },
      {
        id: "e2-drop-m-pg-2",
        name: "MEN",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/mens-eyeglasses/",
      },
      {
        id: "e2-drop-k-pg-3",
        name: "KIDS",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/youth/",
      },
      {
        id: "e2-drop-af-pg-4",
        name: "ALL_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/eyeglasses/",
      },
      {
        id: "e2-drop-bs-pg-5",
        name: "BEST_SELLERS",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/best-seller-glasses",
      },
      {
        id: "e2-drop-fuf-pg-6",
        name: "FRAMES_UNDER_FIFTY",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/eyeglasses-under-50",
      },
      {
        id: "e2-drop-mf-pg-7",
        name: "METAL_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/eyeglasses/metal-frames",
      },
      {
        id: "e2-drop-pf-pg-8",
        name: "PLASTIC_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/eyeglasses/plastic-frames",
      },
      {
        id: "e2-drop-rf-pg-9",
        name: "RIMLESS_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/eyeglasses/rimless-frames",
      },
      {
        id: "e2-drop-cef-pg-10",
        name: "CAT_EYE_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/eyeglasses/cat-eye-frames",
      },
      {
        id: "e2-drop-of-pg-11",
        name: "OVAL_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/eyeglasses/oval-frames ",
      },
      {
        id: "e2-drop-rf-pg-12",
        name: "RECTANGLE_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/eyeglasses/rectangle-frames",
      },
      {
        id: "e2-drop-rf-pg-13",
        name: "ROUND_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/eyeglasses/round-frames",
      },
      {
        id: "e2-drop-sf-pg-14",
        name: "SQUARE_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/eyeglasses/square-frames",
      },
    ],
    url: "",
  },
  {
    id: "s4-drop",
    name: "SUNGLASSES",
    subMenu: [
      {
        id: "s4-drop-w-pg-1",
        name: "WOMEN",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/womens-sunglasses/",
      },
      {
        id: "s4-drop-m-pg-2",
        name: "MEN",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/mens-sunglasses/",
      },
      {
        id: "e2-drop-af-pg-3",
        name: "ALL_SUNGLASSES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/sunglasses/",
      },
      {
        id: "e2-drop-mf-pg-4",
        name: "METAL_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/sunglasses/metal-frames",
      },
      {
        id: "e2-drop-pf-pg-5",
        name: "PLASTIC_FRAMES",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/sunglasses/plastic-frames",
      },
    ],
    type: NAV_ITEMS.NAV_TYPES.DROPDOWN,
    url: "",
  },
  {
    id: "cl3-drop",
    name: "CONTACT_LENSES",
    subMenu: [
      {
        id: "cl3-drop-d-pg-1",
        name: "DAILY",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/daily-contacts/",
      },
      {
        id: "cl3-drop-m-pg-2",
        name: "MONTHLY",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/monthly-contacts/",
      },
      {
        id: "cl3-drop-bw-pg-3",
        name: "BI_WEEKLY",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/bi-weekly-contacts/",
      },
      {
        id: "cl3-drop-ac-pg-4",
        name: "ALL_CONTACTS",
        subMenu: [],
        type: NAV_ITEMS.NAV_TYPES.TEXT,
        url: "/catalog/contacts/",
      },
      // TODO: 2330 - Uncomment if this page is required
      // {
      //   id: "cl3-drop-sbb-pg-5",
      //   name: "SHOP_BY_BRAND",
      //   subMenu: [],
      //   type: NAV_ITEMS.NAV_TYPES.TEXT,
      //   url: "",
      // },
    ],
    type: NAV_ITEMS.NAV_TYPES.DROPDOWN,
    url: "",
  },
  {
    id: "snm5-text",
    name: "STORES_NEAR_ME",
    subMenu: [],
    type: NAV_ITEMS.NAV_TYPES.TEXT,
    url: "/schedule-exam",
  },
  {
    id: "bo6-text",
    name: "BEST_OFFERS",
    subMenu: [],
    type: NAV_ITEMS.NAV_TYPES.TEXT,
    url: "/special-offers",
  },
  {
    id: "i7-text",
    name: "INSURANCE",
    subMenu: [],
    type: NAV_ITEMS.NAV_TYPES.TEXT,
    url: "/vision-insurance",
  },
];

export const MOBILE_MY_ACCOUNT_ITEMS: NavItem[] = [
  {
    id: "my-it-1",
    name: "ACCOUNT_PROFILE",
    type: "text",
    url: "/my-account/my-profile",
    subMenu: [],
  },
  {
    id: "my-it-2",
    name: "APPOINTMENTS",
    type: "text",
    url: "/my-account/my-appointments",
    subMenu: [],
  },
  {
    id: "my-it-3",
    name: "EYE_HEALTH",
    type: "text",
    url: "/my-account/my-prescriptions",
    subMenu: [],
  },
  {
    id: "my-it-4",
    name: "ASK_DOCTOR",
    type: "text",
    url: "/my-account/ask-a-doctor",
    subMenu: [],
  },
  {
    id: "my-it-5",
    name: "ORDER_HISTORY",
    type: "text",
    url: "/my-account/order-history",
    subMenu: [],
  },
  {
    id: "my-it-6",
    name: "FAVORITES",
    type: "text",
    url: "/my-account/my-favorites",
    subMenu: [],
  },
  {
    id: "my-it-7",
    name: "LOYALTY_CLUB",
    type: "text",
    url: "/my-account/loyalty-club",
    subMenu: [],
  },
];

export const MODIFY_APPOINTMENT_COOKIE = "modify-appointment-flow";
