import BackdropLoader from "@/components/backdrop_loader/BackdropLoader";
import CommonTabsTablePageSkeleton from "@/components/skeleton_loader/CommonTablePageSkeleton/CommonTabsTablePageSkeleton";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const StagingBinViewComponent = dynamic(() => import("order/StagingBinView"), {
  ssr: false,
  loading: () => (
    <CommonTabsTablePageSkeleton
      rows={20}
      columns={15}
      headSkeletonHeight={20}
      bodySkeletonHieght={30}
    />
  ),
});

export default function StagingBinView() {
  const router = useRouter();
  useEffect(() => {
    let isCDCUser = false;
    if (
      localStorage?.getItem("isCDCUser") !== undefined &&
      localStorage.getItem("isCDCUser") === "1"
    ) {
      isCDCUser = true;
    } else {
      isCDCUser = false;
    }

    if (!isCDCUser) {
      router.push("/");
    }
  }, []);
  return (
    <>
      <Head>
        <title>IRIS | Staging Bin View </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <StagingBinViewComponent />
      </div>
    </>
  );
}
