name: Build and Deploy Turborepo Host App

on:
  push:
    branches:
      - Development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the Turborepo
        run: pnpm build

      - name: Prepare standalone build output
        run: |
          mkdir -p deploy
          cp -r apps/host/.next/standalone/* deploy/
          cp -r apps/host/public deploy/public
          cp -r apps/host/.next/static deploy/.next/static

      - name: Zip deploy folder
        run: |
          cd deploy
          zip -r ../output.zip .

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: output.zip

      # OPTIONAL: Add deployment step depending on your hosting provider.
      # For example, Azure App Service:
      # - name: Deploy to Azure App Service
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: <your-app-name>
      #     publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
      #     package: output.zip
