version: '3.8'

services:
  host:
    build:
      context: .
      dockerfile: apps/host/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_HOME=http://localhost:3001
      - NEXT_PUBLIC_APP_HOST=http://localhost:3000
    volumes:
      - ./apps/host:/app
      - /app/node_modules
      - /app/.next
    command: pnpm dev

  home:
    build:
      context: .
      dockerfile: apps/home/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_HOME=http://localhost:3001
      - NEXT_PUBLIC_APP_HOST=http://localhost:3000
    volumes:
      - ./apps/home:/app
      - /app/node_modules
      - /app/.next
    command: pnpm dev 