import TablePageSkeleton from "@/components/skeleton_loader/ManagedCareSkeleton/TablePageSkeleton/TablePageSkeleton";
import dynamic from "next/dynamic";
import Head from "next/head";

const BillingClaimStatusComponent = dynamic(
  () => import("managedCare/BillingClaimStatus"),
  {
    ssr: false,
    loading: () => <TablePageSkeleton />,
  }
);

export default function BillingClaimStatus() {
  return (
    <>
      <Head>
        <title>IRIS | Billing Claim Status</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <BillingClaimStatusComponent />
    </>
  );
}
