import dynamic from "next/dynamic";
import Head from "next/head";

const CptCodeAndProductTypeComponent = dynamic(
  () => import("managedCare/CptCodeAndProductType"),
  {
    ssr: false,
  }
);

export default function CptCodeAndProductType() {
  return (
    <>
      <Head>
        <title>IRIS | CPT Code and Product Type</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <CptCodeAndProductTypeComponent />
    </>
  );
}
