import TablePageSkeleton from "@/components/skeleton_loader/ManagedCareSkeleton/TablePageSkeleton/TablePageSkeleton";
import dynamic from "next/dynamic";
import Head from "next/head";

const InsuranceCarriersComponent = dynamic(
  () => import("managedCare/InsuranceCarriers"),
  {
    ssr: false,
    loading: () => <TablePageSkeleton />,
  }
);

export default function ManagedCare() {
  return (
    <>
      <Head>
        <title>Managed care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <InsuranceCarriersComponent />
      </div>
    </>
  );
}
