import TablePageSkeleton from "@/components/skeleton_loader/ManagedCareSkeleton/TablePageSkeleton/TablePageSkeleton";
import dynamic from "next/dynamic";
import Head from "next/head";

const InsuranceCarrierCredentialsComponent = dynamic(
  () => import("managedCare/InsuranceCarrierCredentials"),
  {
    ssr: false,
    loading: () => <TablePageSkeleton />,
  }
);

export default function InsuranceCarrierCredentials() {
  return (
    <>
      <Head>
        <title>IRIS | Insurance Carrier Credentials </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <InsuranceCarrierCredentialsComponent />
    </>
  );
}
