import RuleSkeleton from "@/components/skeleton_loader/ManagedCareSkeleton/RuleSkeleton/RuleSkeleton";
import dynamic from "next/dynamic";
import Head from "next/head";

const RuleComponent = dynamic(() => import("managedCare/Rule"), {
  ssr: false,
  loading: () => <RuleSkeleton />,
});

export default function Rule() {
  return (
    <>
      <Head>
        <title>IRIS | Rule </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <RuleComponent />
      </div>
    </>
  );
}
