import dynamic from "next/dynamic";
import Head from "next/head";
import SetupSkeleton from "@/components/skeleton_loader/setup/setupSkeleton";

const MasterSetupComponent = dynamic(() => import("setup/MasterSetup"), {
  ssr: false,
  loading: () => <SetupSkeleton tabsCount={10} type="master" />,
});

export default function MasterSetup() {
  return (
    <>
      <Head>
        <title>IRIS | Master Setup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <main>
        <MasterSetupComponent />
      </main>
    </>
  );
}
