import dynamic from "next/dynamic";
import Head from "next/head";
import SetupSkeleton from "@/components/skeleton_loader/setup/setupSkeleton";

const OrderSetupComponent = dynamic(() => import("setup/Order"), {
  ssr: false,
  loading: () => <SetupSkeleton tabsCount={8} />,
});

export default function MasterSetup() {
  return (
    <>
      <Head>
        <title>IRIS | Order Setup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <main>
        <OrderSetupComponent />
      </main>
    </>
  );
}
