import BackdropLoader from "@/components/backdrop_loader/BackdropLoader";
import CommonTabsTablePageSkeleton from "@/components/skeleton_loader/CommonTablePageSkeleton/CommonTabsTablePageSkeleton";
import dynamic from "next/dynamic";
import Head from "next/head";

const PatientCommunication = dynamic(
  () => import("patientCommunication/patientCommunication"),
  {
    ssr: false,
    loading: () => (
      <CommonTabsTablePageSkeleton
        rows={7}
        columns={5}
        headSkeletonHeight={20}
        bodySkeletonHieght={30}
        showTabs={true}
        tabsCount={4}
      />
    ),
  }
);

const Index = () => {
  return (
    <>
      <Head>
        <title>IRIS | Patient Communication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <PatientCommunication />
      </main>
    </>
  );
};

export default Index;
