import dynamic from "next/dynamic";
import Head from "next/head";
import { useRouter } from "next/router";
import MyAccountLoader from "@/components/skeleton_loader/myAccount/MyAccountLoader";
import {
  USER_TYPE,
  menuItemConstants,
  subMenuItems,
} from "@root/host/src/constants/common.constants";
// import { MyAccountDTO } from "@root/patient/src/types/MyAccount.types";
import { useHasInHousePxsContext } from "@/contexts/ HasInHousePxs/ HasInHousePxsContext";
import { useContext, useEffect, useState } from "react";
import { RuntimeVarContext } from "@/contexts/RuntimeVarContext";
import { getDetails } from "@root/host/src/utils/getSessionData";
const MyAccount = dynamic(() => import("patient/MyAccount"), {
  ssr: false,
  loading: () => <MyAccountLoader />,
}) as React.FunctionComponent<any>;

export default function MyAccountProfile() {
  const envContext = useContext(RuntimeVarContext);
  const router = useRouter();
  const { menuItem } = router.query;
  const [userType, setUserType] = useState(USER_TYPE.ANONYMOUS);
  const { userHasInHousePxs, checkPrescriptionData } =
    useHasInHousePxsContext();

  useEffect(() => {
    if (menuItem === "ask-a-doctor" && userHasInHousePxs.myAcct === false) {
      router.push("/my-account/my-profile/");
    }
  }, [userHasInHousePxs.myAcct]);

  useEffect(() => {
    getDetails().then((user) => {
      setUserType(
        user?.authData?.userType
          ? user?.authData?.userType
          : USER_TYPE.ANONYMOUS
      );
    });
  }, [typeof window !== "undefined" && localStorage.getItem("session")]);

  useEffect(() => {
    if (userType === USER_TYPE.ASSOCIATE) {
      router.push("/");
    }
  }, [userType]);

  const items: any = {
    "my-profile": menuItemConstants.MY_ACCOUNT_PROFILE,
    "my-appointments": menuItemConstants.MY_ACCOUNT_APPOINTMENT,
    "my-prescriptions": subMenuItems.MY_ACCOUNT_PRESCRIPTION,
    "my-favorites": menuItemConstants.MY_ACCOUNT_FAVORITES,
    "order-history": menuItemConstants.MY_ACCOUNT_ORDER_HISTORY,
    "after-visit-summary": subMenuItems.MY_ACCOUNT_AFTER_VISIT_SUMMARY,
    "exam-intake-form": subMenuItems.MY_ACCOUNT_MEDICAL_FORM,
    // TODO: Uncomment this when required removed as per ticket [IR24-4452]
    // "vision-intake" : subMenuItems.MY_ACCOUNT_VISION_INTAKE,
    "eye-health": subMenuItems.MY_ACCOUNT_PRESCRIPTION,
    "loyalty-club": menuItemConstants.MY_ACCOUNT_LOYALTY_CLUB,
    "ask-a-doctor": menuItemConstants.MY_ACCOUNT_DOCTOR_CONSULTATION,
  };

  return (
    <>
      <Head>
        <title>My Account | Stanton Optical</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {userType !== USER_TYPE.ASSOCIATE && (
        <MyAccount
          selectedMenuItem={items[menuItem as string]}
          doctorConsultation={{
            userHasInHousePxs: userHasInHousePxs.myAcct || false,
            checkPrescriptionData,
          }}
          env={envContext}
        />
      )}
    </>
  );
}
