import ForgotPasswordPage from "@/components/authentication/ForgotPasswordPage/ForgotPasswordPage";
import SignUpPage from "@/components/authentication/SignUpPage/SignUpPage";
import BackdropLoader from "@/components/backdrop_loader/BackdropLoader";
import {
  USER_TYPE,
  menuItemConstants,
  subMenuItems,
} from "@/constants/common.constants";
import { useHasInHousePxsContext } from "@/contexts/ HasInHousePxs/ HasInHousePxsContext";
import { RuntimeVarContext } from "@/contexts/RuntimeVarContext";
import { MyAccountDTO } from "@root/patient/src/types/MyAccount.types";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";

const MyAccount = dynamic(() => import("patient/MyAccount"), {
  ssr: false,
  loading: () => <BackdropLoader openLoader={true} />,
}) as React.FunctionComponent<MyAccountDTO>;

export default function MyAccountProfile() {
  const env = useContext(RuntimeVarContext);
  const { menuItem } = useRouter().query;
  const items: any = {
    profile: menuItemConstants.MY_ACCOUNT_PROFILE,
    appointments: menuItemConstants.MY_ACCOUNT_APPOINTMENT,
    prescription: subMenuItems.MY_ACCOUNT_PRESCRIPTION,
    favorites: menuItemConstants.MY_ACCOUNT_FAVORITES,
    orderHistory: menuItemConstants.MY_ACCOUNT_ORDER_HISTORY,
    afterVisitSummary: subMenuItems.MY_ACCOUNT_AFTER_VISIT_SUMMARY,
    medicalForm: subMenuItems.MY_ACCOUNT_MEDICAL_FORM,
    "eye-health": subMenuItems.MY_ACCOUNT_PRESCRIPTION,
    loyaltyClub: menuItemConstants.MY_ACCOUNT_LOYALTY_CLUB,
  };
  const router = useRouter();
  const { view } = router.query;

  const { userHasInHousePxs, checkPrescriptionData } =
    useHasInHousePxsContext();
  const [session, setSession] = useState<any>(null);

  useEffect(() => {
    if (localStorage.getItem("session")) {
      setSession(JSON.parse(localStorage.getItem("session") as string));
    }
  }, [typeof window !== "undefined" && localStorage.getItem("session")]);

  useEffect(() => {
    if (localStorage.getItem("session")) {
      const sessionCheck = JSON.parse(
        localStorage.getItem("session") as string
      );
      if (sessionCheck?.user?.authData?.userType === USER_TYPE.ASSOCIATE) {
        router.push("/");
      } else if (sessionCheck?.user?.authData?.userType === USER_TYPE.PATIENT) {
        if (view === "forgot-password") {
          router.push("/my-account");
        }
      }
    }
  }, [typeof window !== "undefined" && localStorage.getItem("session")]);

  return (
    <>
      <>
        {typeof session != "undefined" && (
          <>
            {session?.user?.authData?.userType !== USER_TYPE.ASSOCIATE &&
              (session ? (
                <>
                  <Head>
                    <title>My Account | Stanton Optical</title>
                    <meta
                      name="description"
                      content="Generated by create next app"
                    />
                    <meta
                      name="viewport"
                      content="width=device-width, initial-scale=1"
                    />
                  </Head>
                  <MyAccount
                    selectedMenuItem={menuItemConstants.MY_ACCOUNT_PROFILE}
                    doctorConsultation={{
                      userHasInHousePxs: userHasInHousePxs.myAcct || false,
                      checkPrescriptionData,
                    }}
                    env={env}
                  />
                </>
              ) : view === "forgot-password" ? (
                <>
                  <Head>
                    <title>
                      Forgot Password - My Account - Stanton Optical
                    </title>
                    <meta
                      name="description"
                      content="Forgot your password, you're not the one. Visit this page, follow the instructions and initiate for a new password to recover your account."
                    />
                    <meta name="keywords" content="" />
                    <meta
                      name="viewport"
                      content="width=device-width, initial-scale=1"
                    />
                  </Head>
                  <div>
                    <ForgotPasswordPage />
                  </div>
                </>
              ) : (
                <>
                  <Head>
                    <title>Sign Up - Stanton Optical</title>
                    <meta
                      name="description"
                      content="Sign up and explore Stanton Optical's range of eyeglasses, sunglasses and contact lenses online. We offers one of the America's best eyewear collection for all ages."
                    />
                    <meta name="keywords" content="" />
                    <meta
                      name="viewport"
                      content="width=device-width, initial-scale=1"
                    />
                  </Head>
                  <div>
                    <SignUpPage />
                  </div>
                </>
              ))}
          </>
        )}
      </>
    </>
  );
}
