import { FavoriteProductsAsGuest } from "@/components/favorite-products-as-guest";
import Head from "next/head";

export default function MyFavorites(): React.JSX.Element {
  return (
    <>
      <Head>
        <title>My Favorites | Stanton Optical</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <FavoriteProductsAsGuest />
      </main>
    </>
  );
}
