apiVersion: apps/v1
kind: Deployment
metadata:
  name: host
  namespace: nowoptics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: host
  template:
    metadata:
      labels:
        app: host
    spec:
      containers:
      - name: host
        image: nowoptics/host:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: nowoptics-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20 