export const getPatientEyeGlassHeaders = (
  sphereOptions: string[],
  axisOptions: string[],
  cylinderOptions: string[],
  addOptions: string[],
  monoPdOptions: string[],
  prismOptions: string[],
  sphereHelpText: string,
  cylinderHelpText: string,
  axisHelpText: string,
  addHelpText: string,
  monoPdHelpText: string,
  prismHelpText: string
) => {
  const headers = [
    {
      name: "Sphere",
      displayName: "Sphere (SPH)",
      inputType: "multiColumnSelect",
      options: sphereOptions,
      leftOptions: sphereOptions,
      rightOptions: sphereOptions,
      helpText: sphereHelpText,
      default: "",
    },
    {
      name: "Cylinder",
      displayName: "Cylinder",
      inputType: "multiColumnSelect",
      options: cylinderOptions,
      leftOptions: cylinderOptions,
      rightOptions: cylinderOptions,
      helpText: cylinderHelpText,
      default: "",
    },
    {
      name: "Axis",
      displayName: "Axis",
      inputType: "select",
      options: axisOptions,
      leftOptions: axisOptions,
      rightOptions: axisOptions,
      helpText: axisHelpText,
      default: "",
    },
    {
      name: "Add",
      displayName: "Add",
      inputType: "select",
      options: addOptions,
      leftOptions: addOptions,
      rightOptions: addOptions,
      helpText: addHelpText,
      default: "",
    },
    {
      name: "MonoPd",
      displayName: "Mono PD",
      inputType: "select",
      options: monoPdOptions,
      leftOptions: monoPdOptions,
      rightOptions: monoPdOptions,
      helpText: monoPdHelpText,
      default: "",
    },
    {
      name: "PrismInOut",
      displayName: "Prism In/Out",
      inputType: "selectPrismInOut",
      options: prismOptions,
      leftOptions: prismOptions,
      rightOptions: prismOptions,
      helpText: prismHelpText,
      default: "",
    },
    {
      name: "PrismUpDown",
      displayName: "Prism Up/Down",
      inputType: "selectPrismUpDown",
      options: prismOptions,
      leftOptions: prismOptions,
      rightOptions: prismOptions,
      helpText: prismHelpText,
      default: "",
    },
  ];
  return headers;
};
