export const TabletCheckTableHeader = [
    {
      id: "arrived",
      name: "Arrived",
      isSort: false,
      isFilter: false,
      type: "string",
      width: 500,
    },
    {
      id: "AppointmentTime",
      name: "Appt Time",
      isSort: false,
      isFilter: false,
      type: "string",
      width: 250,
    },
    {
      id: "LastName",
      name: "Last Name",
      isSort: true,
      isFilter: true,
      type: "string",
      width: 250,
    },
    {
      id: "FirstName",
      name: "First Name",
      isSort: true,
      isFilter: true,
      type: "string",
      width: 200,
    },
    {
      id: "Dob",
      name: "DOB",
      isSort: true,
      isFilter: true,
      type: "string",
      width: 200,
    },
    {
      id: "AppointmentType",
      name: "AppointmentType",
      isSort: true,
      isFilter: true,
      type: "string",
      width: 100,
    },
  ];
  