import dynamic from "next/dynamic";
import Head from "next/head";
import SetupSkeleton from "@/components/skeleton_loader/setup/setupSkeleton";

const ContactLensRebatesComponent = dynamic(
  () => import("setup/ContactLensRebates"),
  {
    ssr: false,
    loading: () => <SetupSkeleton tabsCount={8} />,
  }
);

export default function ContactLensRebates() {
  return (
    <>
      <Head>
        <title>IRIS | Contact Lens Rebates</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <ContactLensRebatesComponent />
      </main>
    </>
  );
}
